name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install

      - name: Run Linter
        run: npm run lint -- --fix

      - name: Check for Circular Dependencies
        run: npm run check-circular-deps

      - name: Build Project
        run: npm run build

      - name: List Build Directory
        run: ls -alh ./

      - name: Deploy to EC2
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          SOURCE: "./"
          REMOTE_HOST: ${{ secrets.EC2_HOST }}
          REMOTE_USER: ${{ secrets.EC2_USER }}
          TARGET: "/home/ubuntu/myapp"

      - name: Send mail on failure
        if: failure()
        run: |
          echo "Build job of jain-nabhi966/test failed. Please check the CI/CD pipeline logs for details." > email-body.txt
          echo "" >> email-body.txt
          echo "-------- CI/CD Pipeline Logs --------" >> email-body.txt
          tail -n 10000 $GITHUB_WORKSPACE/runner.log >> email-body.txt  # Adjust the number of lines as needed
          cat email-body.txt
          echo "::set-output name=email_body::$(cat email-body.txt)"

      - name: Send mail on success
        if: success()
        run: |
          echo "Build job of jain-nabhi966/test succeeded." > email-body.txt
          echo "::set-output name=email_body::$(cat email-body.txt)"

      - name: Email notification
        if: ${{ always() }}
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: ${{ job.status == 'success' ? 'Github Actions job succeeded' : 'Github Actions job failed' }}
          to: mrjain1701@gmail.com
          from: Lendbox
          body: |
            ${{ steps.email-notification.outputs.email_body }}

