name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install

      - name: Run Linter
        run: npm run lint -- --fix

      - name: Check for Circular Dependencies
        run: npm run check-circular-deps

      - name: Build Project
        run: npm run build

      - name: List Build Directory
        run: ls -alh ./

      - name: Deploy to EC2
        uses: easingthemes/ssh-deploy@6d9c855f898abc2647afbd20c6e0e6d616c01de8
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          SOURCE: "./"
          REMOTE_HOST: ${{ secrets.EC2_HOST }}
          REMOTE_USER: ${{ secrets.EC2_USER }}
          TARGET: "/home/ubuntu/myapp"

      - name: Send mail on failure
        if: failure()
        uses: dawidd6/action-send-mail@08c4b5e1f425d7b690de3a11a1c2d4ed5c6b3baf
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: Github Actions job failed
          to: mrjain1701@gmail.com
          from: Lendbox
          body: |
            Build job of jain-nabhi966/test failed. Please check the CI/CD pipeline logs for details.

      - name: Send mail on success
        if: success()
        uses: dawidd6/action-send-mail@08c4b5e1f425d7b690de3a11a1c2d4ed5c6b3baf
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: Github Actions job succeed
          to: mrjain1701@gmail.com
          from: Lendbox
          body: |
            Build job of jain-nabhi966/test succeed.
