name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install

      - name: Run Linter
        run: npm run lint -- --fix

      - name: Check for Circular Dependencies
        run: npm run check-circular-deps

      - name: Build Project
        run: npm run build

      - name: List Build Directory
        run: ls -alh ./

      - name: Deploy to EC2
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          SOURCE: "./"
          REMOTE_HOST: ${{ secrets.EC2_HOST }}
          REMOTE_USER: ${{ secrets.EC2_USER }}
          TARGET: "/home/ubuntu/myapp"

      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:
          connection_url: smtps://${{secrets.MAIL_USERNAME}}:${{secrets.MAIL_PASSWORD}}@smtp.gmail.com:465
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: Github Actions job result
          to: jain.nabhi966@gmail.com
          from: Lendbox
          body: Build job of ${{github.repository}} completed successfully!
