name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build

      - name: List Root Directory
        run: ls -alh

      - name: List Potential Build Directories
        run: |
          echo "Listing ./build directory:"
          ls -alh ./build || echo "./build directory does not exist"
          echo "Listing ./dist directory:"
          ls -alh ./dist || echo "./dist directory does not exist"

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Debug SSH Connection
        run: |
          echo "Testing SSH connection"
          ssh -o StrictHostKeyChecking=no -vvv ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} echo "SSH connection established"

      - name: Deploy to EC2
        env:
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_HOST: ${{ secrets.EC2_HOST }}
        run: |
          BUILD_DIR=./build
          if [ ! -d "$BUILD_DIR" ]; then
            BUILD_DIR=./dist
          fi
          if [ -d "$BUILD_DIR" ]; then
            scp -o StrictHostKeyChecking=no -r $BUILD_DIR/* ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/home/ubuntu/myapp/build
            ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
cd /home/ubuntu/myapp/build
# Install pm2 if not already installed
if ! command -v pm2 &> /dev/null
then
  npm install -g pm2
fi
# Install production dependencies
npm install --production
# Restart the application using pm2
pm2 delete all || true
pm2 start npm --name "myapp" -- run start
EOF
          else
            echo "Build directory not found. Deployment skipped."
            exit 1
          fi
