name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Clone Another Repository
        run: |
          git clone https://github.com/your-username/another-repo.git
          cd another-repo
          npm install
          npm run build

      - name: List Build Directory
        run: ls -alh ./another-repo/build

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Debug SSH Connection
        run: |
          echo "Testing SSH connection"
          ssh -o StrictHostKeyChecking=no -vvv ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} echo "SSH connection established"

      - name: Deploy to EC2
        env:
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_HOST: ${{ secrets.EC2_HOST }}
        run: |
          scp -o StrictHostKeyChecking=no -r ./another-repo/build/* ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/home/ubuntu/build
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          cd /home/ubuntu/build
          # Install pm2 if not already installed
          if ! command -v pm2 &> /dev/null
          then
            npm install -g pm2
          fi
          # Install production dependencies
          npm install --production
          # Restart the application using pm2
          pm2 delete all || true
          pm2 start npm --name "myapp" -- run start
          EOF
