name: CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Build Project
        run: npm run build

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v2
        with:
          name: production-files
          path: ./build

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Ensure deployment runs after successful build

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.email "jain.nabhi966@gmail.com"
          git config --global user.name "GitHub Actions"

      - name: Check for changes
        id: check_changes
        run: |
          git status --porcelain
          if [ -z "$(git status --porcelain)" ]; then
            echo "No changes detected. Exiting."
            exit 0
          else
            echo "Changes detected. Proceeding with commit."
          fi

      - name: Set Git Remote URL
        run: git remote set-url origin https://github.com/jain-nabhi966/Webtech-Project.git || true

      - name: Commit and Push Changes
        if: steps.check_changes.outputs.result == 'Changes detected. Proceeding with commit.'
        run: |
          git add .
          git commit -m "Automated deployment commit"
          git push
